### ISSUE TITLE
not symmetric BP score - "L" calculation

### ISSUE THREAD

**Issue by mzuer** [rz6/bp-metric#1]
Dear "rz6",
I read with great interest the article describing BPscore on bioarchiv, and I wanted to test it. By doing so with some toy data, I realized that I do not obtain a same score depending on the order I pass the files using the --tads1 and --tads2 command line arguments; a behaviour that, if I understood correctly, is not desirable. 
I might be wrong, but by looking at the code, I have the impression that this line might be problematic:
        L = (oc.end1-oc.start1).sum()
as indeed, if domain(s) from the 1st set of TADs  have multiple matches in the 2nd set of TADs, then some rows of "oc" will be duplicated, isn't it ?
So to have a symmetric BPscore and discard duplicates, I would say that "L" should be calculated with something like:
        tmpDT = oc.copy()
        tmpDT = tmpDT.loc[:,['start1',  'end1']].drop_duplicates()
        L = (tmpDT.end1 - tmpDT.start1).sum()
Now, the BPscore is the same using --tads1 file1.txt --tads2 file2.txt OR --tads1 file2.txt --tads2 file1.txt

Is my reasoning correct or was the BP score not symmetric on purpose ?

Thanks in advance and best regards

**Comment by rz6** [comment]
Dear "mzuer",
thank you for valuable remark, you are correct, it is undesirable. The fix is pushed, so I'm closing this issue.
